# Setup
title:        Automatic Diagnosis of Language Delays in Children
tagline:      Using Supervised Learning to classify wordless narratives from the CHILDES Talkbank
baseurl:      ""
paginate:     1
exclude: ['README.md']

# About/contact
author:       
  name:       David O'Keeffe
  url:        http://dgokeeffe.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
