# Setup
title:        Diagnosing Language Delays in Children Automatically
tagline:      A machine learning project using data from the CHILDES Talkbank
baseurl:      ""
paginate:     1

# About/contact
author:       David O'Keeffe
  name:       David O'Keeffe
  url:        http://dgokeeffe.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
